### PR TITLE
docs: add Hardhat integration page

### PR DESCRIPTION
**Pull request by devanonon**
This has been asked a few times in the Telegram group now.

### CODE REVIEW

**Comment by gakonst** [comment]
I dont understand, what is the problem that this PR is solving? I had seen the suggestion in the Telegram, but admit I didn't get it

**Comment by gakonst** [comment]
Yeah that sounds good @devanonon, basically let's add:
1. Explanation of the problem
2. A test repo which shows this used

**Comment by devanonon** [comment]
Great, thanks @gakonst!

1. Fair point, it wasn't explained in the page I added. Updated now!
2. I created a repo here: https://github.com/devanonon/hardhat-foundry-template - Do you want to clone/push it into foundry-rs? Or if you make a new repo I'm happy to be a contributor on that and push it myself.

**Review by 0xvv — COMMENTED** [review]
Everything is clear and i see no mistakes, good job :+1:

**Pull request merged**
