### PR TITLE
feat(docs): EIP-712 Tutorial

### LINKED ISSUE #159: Add guide for EIP-712 signatures with vm.sign / vm.addr
Explain how EIP712 works and create & verify signatures via the sign & addr cheatcodes https://github.com/Rari-Capital/solmate/blob/7c34ed021cfeeefb1a4bff7e511a25ce8a68806b/src/test/ERC20.t.sol#L89-L103

### PR DESCRIPTION
**Pull request by kulkarohan**
resolves #159

### CODE REVIEW

**Review by gakonst — CHANGES_REQUESTED** [review]
Love the example. 

But maybe something that is easier for people to grok would be just showing how to use `permit` in ERC2612 / DAI? That is something that you'll encounter more frequently! 

i.e. show that instead of doing `approve`-> function that calls `transferFrom` you can do `permit` off-chain and then function that calls `transferFrom` including the `v,r,s` or the `signature`?


On the code pattern:

Can you replace `DSTest` with `forge-std/Test`? Would let you remove the need to specify `VM internal vm` and instantiate it.

Also would recommend moving `EIP_712_DOMAIN_SEPARATOR` and `SIGNED_TICKET_TYPEHASH` into helper fns / state vars? 

some helper fns which make it clearer:
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/ECDSA.sol#L228
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/draft-EIP712.sol#L53-L103

**Comment by kulkarohan** [comment]
hmmm yeah agreed. i'll update

**Comment by gigamesh** [comment]
Sorry to jump in on this thread but something I've been trying to figure out is how to use forge to test a signed message that is provided to the function as a single string:
https://github.com/soundxyz/protocol/blob/63f5219dca6e91ef27e2922c96473dfacaccb400/contracts/ArtistV4.sol#L450

Is there a way to convert the v, r, s into a `bytes signature`?

For context, the way I'm creating the signature is with[ ethers.js's `wallet._signTypedData`
](https://docs.ethers.io/v5/api/signer/#Signer-signTypedData)

**Comment by kulkarohan** [comment]
hey @gigamesh! `bytes signature = abi.encodePacked(r, s, v)` should do the trick

**Comment by gigamesh** [comment]
ah ok super easy - thank you!

**Comment by kulkarohan** [comment]
@gakonst @onbjerg sorry for the absurd delay on this. let me know if any further changes are desired and i'll update ASAP!!

**Review by onbjerg — APPROVED** [review]
LGTM, let's iterate on it if needed :)

**Pull request merged**
