### PR TITLE
rm blank str at directory name 'solidity-scripting'

### PR DESCRIPTION
**Pull request by coldstar1993**

### CODE REVIEW

**Comment by coldstar1993** [comment]
BTW, Foundry is really good tool but unfamiliar to Chinese dev. I schedule to take a translation of the ‘book' for Chinese dev. Any suggestions for me? Or is there someone raising translation & doing this currently?

**Review by mattsse — APPROVED** [review]
nice catch

**Comment by mattsse** [comment]
> BTW, Foundry is really good tool but unfamiliar to Chinese dev. I schedule to take a translation of the ‘book' for Chinese dev. Any suggestions for me? Or is there someone raising translation & doing this currently?

No translation efforts are currently being made. I'm not familiar with how mdbook manages i18n, so we'd first need to figure out how to support additional languages.

**Comment by coldstar1993** [comment]
Then I think I could take a try and be the first one to translate it into Chinese and share it.  
Will raise a PR when done. 
Ping me (luozhixiao1993@gmail.com) if any suggestions, thx!!

**Comment by coldstar1993** [comment]
hi, @mattsse ,  
With plugin '**mdbook-i18n**', we could easily support additional languages. And I tried it today and result is as belows:
https://coldstar1993.github.io/foundrybook/zh/index.html
图片

what do u think of it? ping me if any sugguestions, Thx!

**Pull request merged**
