### PR TITLE
add fuzz show_log docs

### PR DESCRIPTION
**Pull request by Azleal**
updated docs related to https://github.com/foundry-rs/foundry/pull/8387

### CODE REVIEW

**Comment by Azleal** [comment]
hi @mattsse , I'm not sure where this `Environment` come from. So I left it blank for `show_logs`. please tell me if `Environment` should be here. 

https://github.com/foundry-rs/book/blob/59b6071ac995a2d9e7f2f01360401cb176fac98e/src/reference/config/testing.md?plain=1#L373-L377

**Comment by grandizzy** [comment]
> hi @grandizzy @mattsse , I'm not sure where this `Environment` come from. So I left it blank for `show_logs`. please tell me if `Environment` should be here.
> 
> https://github.com/foundry-rs/book/blob/59b6071ac995a2d9e7f2f01360401cb176fac98e/src/reference/config/testing.md?plain=1#L373-L377

Configs within profile can be passed as env vars, for example you can test that new one works if `FOUNDRY_FUZZ_SHOW_LOGS=true`

**Comment by Azleal** [comment]
> Configs within profile can be passed as env vars, for example you can test that new one works if `FOUNDRY_FUZZ_SHOW_LOGS=true`

yeah. i tried `FOUNDRY_FUZZ_SHOW_LOGS=true forge test --vv`, it worked as expected. and I updated the docs.

**Comment by Azleal** [comment]
hi @mattsse ,  could you please review this PR to see if it could be merged.

**Pull request merged**
