### PR TITLE
Updated the NFT tutorial 

### PR DESCRIPTION
**Pull request by Perelyn-sama**
Changes in this pr:
- Fixed typo in solidity scripting tutorial 
- Updated the code for NFT.t.sol in the solmate-ntt tutorial 
- Added a new screenshot to display the project structure 
- Removed `forge-std` from `forge install` in the solmate-nft tutorial 
- Added reference to a repo where I implemented the solidity scripting tutorial.

btw @onbjerg in the solmate tutorial, `forge init hello-foundry` is never used. Do you think It should be added?

Thanks for reading this far, as usual, I'm open to corrections. ^-^

### CODE REVIEW

**Review by onbjerg — APPROVED** [review]
Looks good - one minor nit: can you remove the old image that we no longer use? :)

**Comment by Perelyn-sama** [comment]
Okay, will do.

**Comment by onbjerg** [comment]
That tag is for people who write new docs and I think I just forgot to give it to you when you added the first Anvil overview :smile: @all-contributors add @Perelyn-sama for docs

**Review by onbjerg — APPROVED** [review]

**Comment by Perelyn-sama** [comment]
It's all good. 

Thanks for being supportive as I tried contributing to open source for the first time.

I've fallen in love with it thanks to you and I'm sure I'll be doing it more in my career all thanks to you. ^-^

**Comment by onbjerg** [comment]
You got it, hope to see you around more and thank you for the contributions :smile:

**Pull request merged**
