### PR TITLE
docs: document smt options

### PR DESCRIPTION
**Pull request by shawnharmsen**
issue: https://github.com/foundry-rs/book/issues/301

also added the additional optimizer settings because I didn't see it

https://github.com/foundry-rs/foundry/tree/master/config#additional-optimizer-settings

and

https://github.com/foundry-rs/foundry/tree/master/config#additional-model-checker-settings

### CODE REVIEW

**Review by onbjerg — CHANGES_REQUESTED** [review]
The sections you wrote here are probably better for the `forge build` reference - whatever is in the config reference should follow the format that the rest of the document uses

**Comment by shawnharmsen** [comment]
gotcha does this look like a better place to put it

**Review by 0xvv — APPROVED** [review]
All good :+1:

**Comment by onbjerg** [comment]
Yes, anything that is not in the config reference but is in Foundry is a candidate to be added; feel free to open up an issue or a PR with them :blush:

**Pull request merged**
